var md_布局示意 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Source Han Sans CN',},
        {type:'fontStyle-main',value:[
            ["color","var(--mainColor)"],
            ["background","none"],
            ["background-clip","none"],
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Source Han Sans CN',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.9, 0, 0, 0.9, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","700"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Sans CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Source Han Serif CN',},
        {type:'fontStyle-main',value:[
            ["color","var(--mainColor)"],
            ["background","none"],
            ["background-clip","none"],
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Source Han Serif CN',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.9, 0, 0, 0.9, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","700"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Serif CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];
var md_清新古风 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Aa诗宋体',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(to top,rgb(255, 240, 196),rgb(255, 255, 255))"],
            ["background-clip","text"],
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.05em"],
            ["font-weight","400"],
            ["filter","drop-shadow(0px 0px 0.1em rgba(201, 95, 57, 0.5)) drop-shadow(0px 0px 0.05em rgba(255, 226, 137, 0.5))"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.05em"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.05em"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Aa诗宋体',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","-0.05"],
            ["font-weight","400"],
        ],},
        {type:'fontFamily-gift',value:'Aa诗宋体',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
        {type:"giftIconAsync",value:'',}
    ],
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Aa诗宋体',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(to top,rgba(175, 129, 1, 0.56) 0%,rgba(113, 43, 0, 0.48) 80%,rgba(108, 27, 0, 0.69) 100%),url('../../../img/noise.png') 0 1em/1em,linear-gradient(to top,rgb(165, 124, 0) 0%,rgb(83, 32, 1) 80%,rgb(108, 27, 0) 100%)"],
            ["background-clip","text"],
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.05em"],
            ["font-weight","400"],
            ["filter","contrast(148%) saturate(110%)"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.05em"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.05em"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Aa诗宋体',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","-0.05"],
            ["font-weight","400"],
        ],},
        {type:'fontFamily-gift',value:'Aa诗宋体',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Source Han Serif CN',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(to top,rgb(255, 240, 196),rgb(255, 255, 255))"],
            ["background-clip","text"],
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","drop-shadow(0px 0px 0.1em rgba(201, 95, 57, 0.5)) drop-shadow(0px 0px 0.05em rgba(255, 226, 137, 0.5))"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Aa诗宋体',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","500"],
        ],},
        {type:'fontFamily-gift',value:'Aa诗宋体',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Source Han Serif CN',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(to top,rgb(110, 80, 5),rgb(31, 2, 2))"],
            ["background-clip","text"],
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","contrast(148%) saturate(110%)"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Aa诗宋体',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","500"],
        ],},
        {type:'fontFamily-gift',value:'Aa诗宋体',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Source Han Serif CN',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(45deg,rgba(255, 255, 255, 0) 30%,rgb(255, 255, 255) 50%,rgba(255, 255, 255, 0) 80%),linear-gradient(to top,rgb(255, 255, 255)0%,rgb(255, 230, 148) 60%)"],
            ["background-clip","text"],
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","drop-shadow(0 0 0.1em rgba(123, 42, 12, 0.24)) drop-shadow(0 0.02em 0.01em rgba(58, 33, 10, 0.67))"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Aa诗宋体',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","500"],
        ],},
        {type:'fontFamily-gift',value:'Aa诗宋体',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];
var md_江湖快意 = [
    [
        {type:'giftIconBg',value:haxi + '../img/model/gufeng/bg_icon.png',},
        {type:'fontFamily-main',value:'FZYaSongS-B-GB',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(to top,rgba(255, 230, 155, 0.48),rgba(252, 255, 223, 0.59)),url('../../../img/noise.png') 0 1em/1em, linear-gradient(to top,rgb(255, 230, 155),rgb(252, 255, 223))"],
            ["background-clip","text"],
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","drop-shadow(0 0 0.05em rgba(123, 42, 12, 0.24)) drop-shadow(0 0.01em 0.01em rgba(58, 33, 10, 0.67)) contrast(148%)"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'FZJinLS-B-GB',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
        ],},
        {type:'fontFamily-gift',value:'FZJinLS-B-GB',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
    [
        {type:'giftIconBg',value:haxi + '../img/model/gufeng/bg_icon.png',},
        {type:'fontFamily-main',value:'YouSheBiaoTiHei',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(to top,rgba(179, 3, 3, 0.57) 0%, rgba(122, 0, 0, 0.44) 30%,rgba(21, 19, 19, 0.7) 100% ),url('../../../img/noise.png') 0 1em/1em, linear-gradient(to top,rgb(179, 3, 3) 0%, rgb(122, 0, 0) 30%,rgb(21, 19, 19) 100%)"],
            ["background-clip","text"],
            ["transform","matrix(1.1, 0, 0, 1.35, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","brightness(120%) contrast(148%)"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1.1, 0, 0, 1.35, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1.1, 0, 0, 1.35, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'YouSheBiaoTiHei',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
        ],},
        {type:'fontFamily-gift',value:'FZJinLS-B-GB',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];
var md_艺术书法 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'AaJianHaoTi',},
        {type:'fontStyle-main',value:[
            ["color","var(--mainColor)"],
            ["background","none"],
            ["background-clip","none"],
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.1em"],
            ["font-weight","500"],
            ["filter","none"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.1em"],
            ["font-weight","500"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1.1, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","-0.1em"],
            ["font-weight","500"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Source Han Serif CN',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Serif CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];
var md_经典怀旧 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Source Han Serif CN',},
        {type:'fontStyle-main',value:[
            ["color","var(--mainColor)"],
            ["background","none"],
            ["background-clip","none"],
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'HYXiaoLiShuJ',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.9, 0, 0, 0.9, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Serif CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];
var md_暗黑神秘 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'HYDiWRGJ',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(to top,rgb(255, 240, 196),rgb(255, 255, 255))"],
            ["background-clip","text"],
            ["transform","matrix(1.2, 0, 0, 1.2, 0, 0)"],
            ["letter-spacing","-0.15em"],
            ["font-weight","500"],
            ["filter","drop-shadow(0px 0px 0.1em rgba(201, 95, 57, 0.5)) drop-shadow(0px 0px 0.05em rgba(255, 226, 137, 0.5))"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1.2, 0, 0, 1.2, 0, 0)"],
            ["letter-spacing","-0.15em"],
            ["font-weight","500"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1.2, 0, 0, 1.2, 0, 0)"],
            ["letter-spacing","-0.15em"],
            ["font-weight","500"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'HYDiWRGJ',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.9, 0, 0, 0.9, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","500"],
        ],},
        {type:'fontFamily-gift',value:'HYDiWRGJ',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];
var md_科技硬核 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'CKTKingKong',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(to top,rgb(199, 199, 200),rgb(235, 235, 235))"],
            ["background-clip","text"],
            ["transform","matrix(1, 0, -0.1, 1, 0, 0)"],
            ["letter-spacing","0.05em"],
            ["font-weight","500"],
            ["filter","drop-shadow(0 0 0.1em rgba(38, 38, 39, 0.24)) drop-shadow(0 0.02em 0.01em rgba(23, 25, 29, 0.67)) drop-shadow(0.01em -0.01em 0 rgb(255, 255, 255)) contrast(128%)"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1, 0, -0.1, 1, 0, 0)"],
            ["letter-spacing","0.05em"],
            ["font-weight","500"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1, 0, -0.1, 1, 0, 0)"],
            ["letter-spacing","0.05em"],
            ["font-weight","500"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Source Han Sans CN',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","900"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Sans CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];
var md_搞怪有趣 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'荆南波波黑',},
        {type:'fontStyle-main',value:[
            ["color","transparent"],
            ["background","linear-gradient(-45deg,rgba(255, 255, 255, 0) 30%,rgb(255, 234, 171) 50%,rgba(255, 255, 255, 0) 80%),radial-gradient(ellipse at top center,rgb(255, 218, 106)0%,rgb(255, 245, 211) 80%,rgb(255, 218, 106)100%)"],
            ["background-clip","text"],
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","contrast(128%) saturate(90%)"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0) translate(0, -0.15em)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgb(224, 100, 23)"],
            ["stroke","rgb(224, 100, 23)"],
            ["stroke-width","0.24em"],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0) translate(0, -0.15em)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgb(255, 162, 49)"],
            ["stroke","rgb(255, 162, 49)"],
            ["stroke-width","0.32em"],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'荆南波波黑',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.9, 0, 0, 0.9, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Sans CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","700"],
        ],},
    ],
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'qiantuhouheiti',},
        {type:'fontStyle-main',value:[
            ["color","var(--mainColor)"],
            ["background","none"],
            ["background-clip","none"],
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1, 0, 0, 1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'qiantuhouheiti',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.9, 0, 0, 0.9, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Sans CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","700"],
        ],},
    ],
];
var md_唯美梦幻 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'Source Han Serif CN',},
        {type:'fontStyle-main',value:[
            ["color","var(--mainColor)"],
            ["background","none"],
            ["background-clip","none"],
            ["transform","matrix(0.9, 0, -0.1, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","500"],
            ["filter","none"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(0.9, 0, -0.1, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","500"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(0.9, 0, -0.1, 1.1, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","500"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Source Han Serif CN',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.8, 0, 0, 0.8, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Serif CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'SrcMing',},
        {type:'fontStyle-main',value:[
            ["color","var(--mainColor)"],
            ["background","none"],
            ["background-clip","none"],
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0.1em"],
            ["font-weight","400"],
            ["filter","none"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0.1em"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(0.9, 0, 0, 1.1, 0, 0)"],
            ["letter-spacing","0.1em"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'SrcMing',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.9, 0, 0, 0.9, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Serif CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];
var md_华丽高贵 = [
    [
        {type:'giftIconBg',value:haxi + '../img/bg_icon.png',},
        {type:'fontFamily-main',value:'PangMenZhengDao',},
        {type:'fontStyle-main',value:[
            ["color","var(--mainColor)"],
            ["background","none"],
            ["background-clip","none"],
            ["transform","matrix(1, 0, 0, 1.2, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
        ],},
        {type:'fontStyle-mainS',value:[
            ["transform","matrix(1, 0, 0, 1.2, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontStyle-mainSS',value:[
            ["transform","matrix(1, 0, 0, 1.2, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","400"],
            ["filter","none"],
            ["fill","rgba(0,0,0,0)"],
            ["stroke","rgba(0,0,0,0)"],
            ["stroke-width",10],
            ["stroke-linejoin","round"],
        ],},
        {type:'fontFamily-sec',value:'Source Han Sans CN',},
        {type:'fontStyle-sec',value:[["color","var(--mainColor)"],
            ["transform","matrix(0.9, 0, 0, 0.9, 0, 0)"],
            ["letter-spacing","0"],
            ["font-weight","700"],
        ],},
        {type:'fontFamily-gift',value:'Source Han Sans CN',},
        {type:'fontStyle-gift',value:[["color","var(--mainColor)"],
            ["font-weight","400"],
        ],},
    ],
];

const models = [
    {name:"布局示意",img:"../img/icon_mod_layout.png",styleset:md_布局示意},
    {name:"清新古风",img:"../img/icon_mod_gufeng.png",styleset:md_清新古风},
    {name:"江湖快意",img:"../img/icon_mod_jianghu.png",styleset:md_江湖快意},
    {name:"艺术书法",img:"../img/icon_mod_shufa.png",styleset:md_艺术书法},
    {name:"经典怀旧",img:"../img/icon_mod_jingdian.png",styleset:md_经典怀旧},
    {name:"暗黑神秘",img:"../img/icon_mod_anhei.png",styleset:md_暗黑神秘},
    {name:"科技硬核",img:"../img/icon_mod_yinghe.png",styleset:md_科技硬核},
    {name:"搞怪有趣",img:"../img/icon_mod_youqu.png",styleset:md_搞怪有趣},
    {name:"唯美梦幻",img:"../img/icon_mod_weimei.png",styleset:md_唯美梦幻},
    {name:"华丽高贵",img:"../img/icon_mod_huali.png",styleset:md_华丽高贵},
]